use crate::error::{ErrorType, OairsError};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Language {
    Abkhazian,
    Afar,
    Afrikaans,
    Akan,
    Albanian,
    Amharic,
    Arabic,
    Aragonese,
    Armenian,
    Assamese,
    Avaric,
    Avestan,
    Aymara,
    Azerbaijani,
    Bambara,
    Bashkir,
    Basque,
    Belarusian,
    Bengali,
    Bislama,
    Bosnian,
    Breton,
    Bulgarian,
    Burmese,
    // Valencian
    Catalan,
    Chamorro,
    Chechen,
    // Chewa, Nyanja
    Chichewa,
    Chinese,
    // Old Slavonic, Old Church Slavonic
    ChurchSlavonic,
    Chuvash,
    Cornish,
    Corsican,
    Cree,
    Croatian,
    Czech,
    Danish,
    // Dhivehi, Maldivian
    Divehi,
    // Flemish
    Dutch,
    Dzongkha,
    English,
    Esperanto,
    Estonian,
    Ewe,
    Faroese,
    Fijian,
    Finnish,
    French,
    WesternFrisian,
    Fulah,
    // Scottish Gaelic
    Gaelic,
    Galician,
    Ganda,
    Georgian,
    German,
    // Modern (1453–)
    Greek,
    // Greenlandic
    Kalaallisut,
    Guarani,
    Gujarati,
    // Haitian Creole
    Haitian,
    Hausa,
    Hebrew,
    Herero,
    Hindi,
    HiriMotu,
    Hungarian,
    Icelandic,
    Ido,
    Igbo,
    Indonesian,
    // (International Auxiliary Language Association)
    Interlingua,
    // Occidental
    Interlingue,
    Inuktitut,
    Inupiaq,
    Irish,
    Italian,
    Japanese,
    Javanese,
    Kannada,
    Kanuri,
    Kashmiri,
    Kazakh,
    // Central Khmer
    Khmer,
    // Gikuyu
    Kikuyu,
    Kinyarwanda,
    // Kyrgyz
    Kirghiz,
    Komi,
    Kongo,
    Korean,
    // Kwanyama,
    Kuanyama,
    Kurdish,
    Lao,
    Latin,
    Latvian,
    // Limburger, Limburgish,
    Limburgan,
    Lingala,
    Lithuanian,
    LubaKatanga,
    // Letzeburgesch,
    Luxembourgish,
    Macedonian,
    Malagasy,
    Malay,
    Malayalam,
    Maltese,
    Manx,
    Maori,
    Marathi,
    Marshallese,
    Mongolian,
    Nauru,
    // Navaho,
    Navajo,
    NorthNdebele,
    SouthNdebele,
    Ndonga,
    Nepali,
    Norwegian,
    NorwegianBokmal,
    NorwegianNynorsk,
    // Nuosu,
    SichuanYi,
    Occitan,
    Ojibwa,
    Oriya,
    Oromo,
    // Ossetic,
    Ossetian,
    Pali,
    // Pushto,
    Pashto,
    Persian,
    Polish,
    Portuguese,
    // Panjabi,
    Punjabi,
    Quechua,
    // Moldovan, Moldavian,
    Romanian,
    Romansh,
    Rundi,
    Russian,
    NorthernSami,
    Samoan,
    Sango,
    Sanskrit,
    Sardinian,
    Serbian,
    Shona,
    Sindhi,
    // Sinhalese,
    Sinhala,
    Slovak,
    Slovenian,
    Somali,
    SouthernSotho,
    // Castilian,
    Spanish,
    Sundanese,
    Swahili,
    Swati,
    Swedish,
    Tagalog,
    Tahitian,
    Tajik,
    Tamil,
    Tatar,
    Telugu,
    Thai,
    Tibetan,
    Tigrinya,
    Tonga,
    Tsonga,
    Tswana,
    Turkish,
    Turkmen,
    Twi,
    // Uyghur,
    Uighur,
    Ukrainian,
    Urdu,
    Uzbek,
    Venda,
    Vietnamese,
    Volapuk,
    Walloon,
    Welsh,
    Wolof,
    Xhosa,
    Yiddish,
    Yoruba,
    // Chuang,
    Zhuang,
    Zulu,
}

#[allow(dead_code)]
impl Language {
    pub fn from_iso639_1(code: &str) -> Result<Language, OairsError> {
        match code {
            "ab" => Ok(Language::Abkhazian),
            "aa" => Ok(Language::Afar),
            "af" => Ok(Language::Afrikaans),
            "ak" => Ok(Language::Akan),
            "sq" => Ok(Language::Albanian),
            "am" => Ok(Language::Amharic),
            "ar" => Ok(Language::Arabic),
            "an" => Ok(Language::Aragonese),
            "hy" => Ok(Language::Armenian),
            "as" => Ok(Language::Assamese),
            "av" => Ok(Language::Avaric),
            "ae" => Ok(Language::Avestan),
            "ay" => Ok(Language::Aymara),
            "az" => Ok(Language::Azerbaijani),
            "bm" => Ok(Language::Bambara),
            "ba" => Ok(Language::Bashkir),
            "eu" => Ok(Language::Basque),
            "be" => Ok(Language::Belarusian),
            "bn" => Ok(Language::Bengali),
            "bi" => Ok(Language::Bislama),
            "bs" => Ok(Language::Bosnian),
            "br" => Ok(Language::Breton),
            "bg" => Ok(Language::Bulgarian),
            "my" => Ok(Language::Burmese),
            "ca" => Ok(Language::Catalan),
            "ch" => Ok(Language::Chamorro),
            "ce" => Ok(Language::Chechen),
            "ny" => Ok(Language::Chichewa),
            "zh" => Ok(Language::Chinese),
            "cu" => Ok(Language::ChurchSlavonic),
            "cv" => Ok(Language::Chuvash),
            "kw" => Ok(Language::Cornish),
            "co" => Ok(Language::Corsican),
            "cr" => Ok(Language::Cree),
            "hr" => Ok(Language::Croatian),
            "cs" => Ok(Language::Czech),
            "da" => Ok(Language::Danish),
            "dv" => Ok(Language::Divehi),
            "nl" => Ok(Language::Dutch),
            "dz" => Ok(Language::Dzongkha),
            "en" => Ok(Language::English),
            "eo" => Ok(Language::Esperanto),
            "et" => Ok(Language::Estonian),
            "ee" => Ok(Language::Ewe),
            "fo" => Ok(Language::Faroese),
            "fj" => Ok(Language::Fijian),
            "fi" => Ok(Language::Finnish),
            "fr" => Ok(Language::French),
            "fy" => Ok(Language::WesternFrisian),
            "ff" => Ok(Language::Fulah),
            "gd" => Ok(Language::Gaelic),
            "gl" => Ok(Language::Galician),
            "lg" => Ok(Language::Ganda),
            "ka" => Ok(Language::Georgian),
            "de" => Ok(Language::German),
            "el" => Ok(Language::Greek),
            "kl" => Ok(Language::Kalaallisut),
            "gn" => Ok(Language::Guarani),
            "gu" => Ok(Language::Gujarati),
            "ht" => Ok(Language::Haitian),
            "ha" => Ok(Language::Hausa),
            "he" => Ok(Language::Hebrew),
            "hz" => Ok(Language::Herero),
            "hi" => Ok(Language::Hindi),
            "ho" => Ok(Language::HiriMotu),
            "hu" => Ok(Language::Hungarian),
            "is" => Ok(Language::Icelandic),
            "io" => Ok(Language::Ido),
            "ig" => Ok(Language::Igbo),
            "id" => Ok(Language::Indonesian),
            "ia" => Ok(Language::Interlingua),
            "ie" => Ok(Language::Interlingue),
            "iu" => Ok(Language::Inuktitut),
            "ik" => Ok(Language::Inupiaq),
            "ga" => Ok(Language::Irish),
            "it" => Ok(Language::Italian),
            "ja" => Ok(Language::Japanese),
            "jv" => Ok(Language::Javanese),
            "kn" => Ok(Language::Kannada),
            "kr" => Ok(Language::Kanuri),
            "ks" => Ok(Language::Kashmiri),
            "kk" => Ok(Language::Kazakh),
            "km" => Ok(Language::Khmer),
            "ki" => Ok(Language::Kikuyu),
            "rw" => Ok(Language::Kinyarwanda),
            "ky" => Ok(Language::Kirghiz),
            "kv" => Ok(Language::Komi),
            "kg" => Ok(Language::Kongo),
            "ko" => Ok(Language::Korean),
            "ku" => Ok(Language::Kurdish),
            "lo" => Ok(Language::Lao),
            "la" => Ok(Language::Latin),
            "lv" => Ok(Language::Latvian),
            "li" => Ok(Language::Limburgan),
            "ln" => Ok(Language::Lingala),
            "lt" => Ok(Language::Lithuanian),
            "lu" => Ok(Language::LubaKatanga),
            "lb" => Ok(Language::Luxembourgish),
            "mk" => Ok(Language::Macedonian),
            "mg" => Ok(Language::Malagasy),
            "ms" => Ok(Language::Malay),
            "ml" => Ok(Language::Malayalam),
            "mt" => Ok(Language::Maltese),
            "gv" => Ok(Language::Manx),
            "mi" => Ok(Language::Maori),
            "mr" => Ok(Language::Marathi),
            "mh" => Ok(Language::Marshallese),
            "mn" => Ok(Language::Mongolian),
            "na" => Ok(Language::Nauru),
            "nv" => Ok(Language::Navajo),
            "ng" => Ok(Language::Ndonga),
            "ne" => Ok(Language::Nepali),
            "nd" => Ok(Language::NorthNdebele),
            "se" => Ok(Language::NorthernSami),
            "no" => Ok(Language::Norwegian),
            "nb" => Ok(Language::NorwegianBokmal),
            "nn" => Ok(Language::NorwegianNynorsk),
            "oc" => Ok(Language::Occitan),
            "oj" => Ok(Language::Ojibwa),
            "or" => Ok(Language::Oriya),
            "om" => Ok(Language::Oromo),
            "os" => Ok(Language::Ossetian),
            "pi" => Ok(Language::Pali),
            "pa" => Ok(Language::Punjabi),
            "ps" => Ok(Language::Pashto),
            "fa" => Ok(Language::Persian),
            "pl" => Ok(Language::Polish),
            "pt" => Ok(Language::Portuguese),
            "qu" => Ok(Language::Quechua),
            "rm" => Ok(Language::Romansh),
            "ro" => Ok(Language::Romanian),
            "rn" => Ok(Language::Rundi),
            "ru" => Ok(Language::Russian),
            "sa" => Ok(Language::Sanskrit),
            "sc" => Ok(Language::Sardinian),
            "sd" => Ok(Language::Sindhi),
            "sm" => Ok(Language::Samoan),
            "sg" => Ok(Language::Sango),
            "sr" => Ok(Language::Serbian),
            "sn" => Ok(Language::Shona),
            "ii" => Ok(Language::SichuanYi),
            "si" => Ok(Language::Sinhala),
            "sk" => Ok(Language::Slovak),
            "sl" => Ok(Language::Slovenian),
            "so" => Ok(Language::Somali),
            "st" => Ok(Language::SouthernSotho),
            "nr" => Ok(Language::SouthNdebele),
            "es" => Ok(Language::Spanish),
            "su" => Ok(Language::Sundanese),
            "sw" => Ok(Language::Swahili),
            "ss" => Ok(Language::Swati),
            "sv" => Ok(Language::Swedish),
            "tl" => Ok(Language::Tagalog),
            "ty" => Ok(Language::Tahitian),
            "tg" => Ok(Language::Tajik),
            "ta" => Ok(Language::Tamil),
            "tt" => Ok(Language::Tatar),
            "te" => Ok(Language::Telugu),
            "th" => Ok(Language::Thai),
            "bo" => Ok(Language::Tibetan),
            "ti" => Ok(Language::Tigrinya),
            "to" => Ok(Language::Tonga),
            "ts" => Ok(Language::Tsonga),
            "tn" => Ok(Language::Tswana),
            "tr" => Ok(Language::Turkish),
            "tk" => Ok(Language::Turkmen),
            "tw" => Ok(Language::Twi),
            "ug" => Ok(Language::Uighur),
            "uk" => Ok(Language::Ukrainian),
            "ur" => Ok(Language::Urdu),
            "uz" => Ok(Language::Uzbek),
            "ve" => Ok(Language::Venda),
            "vi" => Ok(Language::Vietnamese),
            "vo" => Ok(Language::Volapuk),
            "wa" => Ok(Language::Walloon),
            "cy" => Ok(Language::Welsh),
            "wo" => Ok(Language::Wolof),
            "xh" => Ok(Language::Xhosa),
            "yi" => Ok(Language::Yiddish),
            "yo" => Ok(Language::Yoruba),
            "za" => Ok(Language::Zhuang),
            "zu" => Ok(Language::Zulu),
            _ => Err(OairsError::new(
                "Invalid language code".to_string(),
                ErrorType::ParamError,
                Some(code.to_string()),
                None,
            )),
        }
    }

    fn as_iso639_1(&self) -> &str {
        match self {
            Language::Abkhazian => "ab",
            Language::Afar => "aa",
            Language::Afrikaans => "af",
            Language::Akan => "ak",
            Language::Albanian => "sq",
            Language::Amharic => "am",
            Language::Arabic => "ar",
            Language::Aragonese => "an",
            Language::Armenian => "hy",
            Language::Assamese => "as",
            Language::Avaric => "av",
            Language::Avestan => "ae",
            Language::Aymara => "ay",
            Language::Azerbaijani => "az",
            Language::Bambara => "bm",
            Language::Bashkir => "ba",
            Language::Basque => "eu",
            Language::Belarusian => "be",
            Language::Bengali => "bn",
            Language::Bislama => "bi",
            Language::Bosnian => "bs",
            Language::Breton => "br",
            Language::Bulgarian => "bg",
            Language::Burmese => "my",
            Language::Catalan => "ca",
            Language::Chamorro => "ch",
            Language::Chechen => "ce",
            Language::Chichewa => "ny",
            Language::Chinese => "zh",
            Language::ChurchSlavonic => "cu",
            Language::Chuvash => "cv",
            Language::Cornish => "kw",
            Language::Corsican => "co",
            Language::Cree => "cr",
            Language::Croatian => "hr",
            Language::Czech => "cs",
            Language::Danish => "da",
            Language::Divehi => "dv",
            Language::Dutch => "nl",
            Language::Dzongkha => "dz",
            Language::English => "en",
            Language::Esperanto => "eo",
            Language::Estonian => "et",
            Language::Ewe => "ee",
            Language::Faroese => "fo",
            Language::Fijian => "fj",
            Language::Finnish => "fi",
            Language::French => "fr",
            Language::Fulah => "ff",
            Language::Gaelic => "gd",
            Language::Galician => "gl",
            Language::Ganda => "lg",
            Language::Georgian => "ka",
            Language::German => "de",
            Language::Greek => "el",
            Language::Kalaallisut => "kl",
            Language::Guarani => "gn",
            Language::Gujarati => "gu",
            Language::Haitian => "ht",
            Language::Hausa => "ha",
            Language::Hebrew => "he",
            Language::Herero => "hz",
            Language::Hindi => "hi",
            Language::HiriMotu => "ho",
            Language::Hungarian => "hu",
            Language::Icelandic => "is",
            Language::Ido => "io",
            Language::Igbo => "ig",
            Language::Indonesian => "id",
            Language::Interlingua => "ia",
            Language::Interlingue => "ie",
            Language::Inuktitut => "iu",
            Language::Inupiaq => "ik",
            Language::Irish => "ga",
            Language::Italian => "it",
            Language::Japanese => "ja",
            Language::Javanese => "jv",
            Language::Kannada => "kn",
            Language::Kanuri => "kr",
            Language::Kashmiri => "ks",
            Language::Kazakh => "kk",
            Language::Khmer => "km",
            Language::Kikuyu => "ki",
            Language::Kinyarwanda => "rw",
            Language::Kirghiz => "ky",
            Language::Komi => "kv",
            Language::Kongo => "kg",
            Language::Korean => "ko",
            Language::Kurdish => "ku",
            Language::Kuanyama => "kj",
            Language::Lao => "lo",
            Language::Latin => "la",
            Language::Latvian => "lv",
            Language::Limburgan => "li",
            Language::Lingala => "ln",
            Language::Lithuanian => "lt",
            Language::LubaKatanga => "lu",
            Language::Luxembourgish => "lb",
            Language::Macedonian => "mk",
            Language::Malagasy => "mg",
            Language::Malay => "ms",
            Language::Malayalam => "ml",
            Language::Maltese => "mt",
            Language::Manx => "gv",
            Language::Maori => "mi",
            Language::Marathi => "mr",
            Language::Marshallese => "mh",
            Language::Mongolian => "mn",
            Language::Nauru => "na",
            Language::Navajo => "nv",
            Language::Ndonga => "ng",
            Language::Nepali => "ne",
            Language::NorthNdebele => "nd",
            Language::NorthernSami => "se",
            Language::Norwegian => "no",
            Language::NorwegianBokmal => "nb",
            Language::NorwegianNynorsk => "nn",
            Language::Occitan => "oc",
            Language::Ojibwa => "oj",
            Language::Oriya => "or",
            Language::Oromo => "om",
            Language::Ossetian => "os",
            Language::Pali => "pi",
            Language::Punjabi => "pa",
            Language::Pashto => "ps",
            Language::Persian => "fa",
            Language::Polish => "pl",
            Language::Portuguese => "pt",
            Language::Quechua => "qu",
            Language::Romansh => "rm",
            Language::Romanian => "ro",
            Language::Rundi => "rn",
            Language::Russian => "ru",
            Language::Sanskrit => "sa",
            Language::Sardinian => "sc",
            Language::Sindhi => "sd",
            Language::Samoan => "sm",
            Language::Sango => "sg",
            Language::Serbian => "sr",
            Language::Shona => "sn",
            Language::SichuanYi => "ii",
            Language::Sinhala => "si",
            Language::Slovak => "sk",
            Language::Slovenian => "sl",
            Language::Somali => "so",
            Language::SouthernSotho => "st",
            Language::SouthNdebele => "nr",
            Language::Spanish => "es",
            Language::Sundanese => "su",
            Language::Swahili => "sw",
            Language::Swati => "ss",
            Language::Swedish => "sv",
            Language::Tagalog => "tl",
            Language::Tahitian => "ty",
            Language::Tajik => "tg",
            Language::Tamil => "ta",
            Language::Tatar => "tt",
            Language::Telugu => "te",
            Language::Thai => "th",
            Language::Tibetan => "bo",
            Language::Tigrinya => "ti",
            Language::Tonga => "to",
            Language::Tsonga => "ts",
            Language::Tswana => "tn",
            Language::Turkish => "tr",
            Language::Turkmen => "tk",
            Language::Twi => "tw",
            Language::Uighur => "ug",
            Language::Ukrainian => "uk",
            Language::Urdu => "ur",
            Language::Uzbek => "uz",
            Language::Venda => "ve",
            Language::Vietnamese => "vi",
            Language::Volapuk => "vo",
            Language::Walloon => "wa",
            Language::Welsh => "cy",
            Language::WesternFrisian => "fy",
            Language::Wolof => "wo",
            Language::Xhosa => "xh",
            Language::Yiddish => "yi",
            Language::Yoruba => "yo",
            Language::Zhuang => "za",
            Language::Zulu => "zu",
        }
    }

    /// Order of items reflects the order found
    /// in the table here: <https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes>
    pub const ALL: [Language; 183] = [
        Language::Abkhazian,
        Language::Afar,
        Language::Afrikaans,
        Language::Akan,
        Language::Albanian,
        Language::Amharic,
        Language::Arabic,
        Language::Aragonese,
        Language::Armenian,
        Language::Assamese,
        Language::Avaric,
        Language::Avestan,
        Language::Aymara,
        Language::Azerbaijani,
        Language::Bambara,
        Language::Bashkir,
        Language::Basque,
        Language::Belarusian,
        Language::Bengali,
        Language::Bislama,
        Language::Bosnian,
        Language::Breton,
        Language::Bulgarian,
        Language::Burmese,
        Language::Catalan,
        Language::Chamorro,
        Language::Chechen,
        Language::Chichewa,
        Language::Chinese,
        Language::ChurchSlavonic,
        Language::Chuvash,
        Language::Cornish,
        Language::Corsican,
        Language::Cree,
        Language::Croatian,
        Language::Czech,
        Language::Danish,
        Language::Divehi,
        Language::Dutch,
        Language::Dzongkha,
        Language::English,
        Language::Esperanto,
        Language::Estonian,
        Language::Ewe,
        Language::Faroese,
        Language::Fijian,
        Language::Finnish,
        Language::French,
        Language::WesternFrisian,
        Language::Fulah,
        Language::Gaelic,
        Language::Galician,
        Language::Ganda,
        Language::Georgian,
        Language::German,
        Language::Greek,
        Language::Kalaallisut,
        Language::Guarani,
        Language::Gujarati,
        Language::Haitian,
        Language::Hausa,
        Language::Hebrew,
        Language::Herero,
        Language::Hindi,
        Language::HiriMotu,
        Language::Hungarian,
        Language::Icelandic,
        Language::Ido,
        Language::Igbo,
        Language::Indonesian,
        Language::Interlingua,
        Language::Interlingue,
        Language::Inuktitut,
        Language::Inupiaq,
        Language::Irish,
        Language::Italian,
        Language::Japanese,
        Language::Javanese,
        Language::Kannada,
        Language::Kanuri,
        Language::Kashmiri,
        Language::Kazakh,
        Language::Khmer,
        Language::Kikuyu,
        Language::Kinyarwanda,
        Language::Kirghiz,
        Language::Komi,
        Language::Kongo,
        Language::Korean,
        Language::Kuanyama,
        Language::Kurdish,
        Language::Lao,
        Language::Latin,
        Language::Latvian,
        Language::Limburgan,
        Language::Lingala,
        Language::Lithuanian,
        Language::LubaKatanga,
        Language::Luxembourgish,
        Language::Macedonian,
        Language::Malagasy,
        Language::Malay,
        Language::Malayalam,
        Language::Maltese,
        Language::Manx,
        Language::Maori,
        Language::Marathi,
        Language::Marshallese,
        Language::Mongolian,
        Language::Nauru,
        Language::Navajo,
        Language::NorthNdebele,
        Language::SouthNdebele,
        Language::Ndonga,
        Language::Nepali,
        Language::Norwegian,
        Language::NorwegianBokmal,
        Language::NorwegianNynorsk,
        Language::SichuanYi,
        Language::Occitan,
        Language::Ojibwa,
        Language::Oriya,
        Language::Oromo,
        Language::Ossetian,
        Language::Pali,
        Language::Pashto,
        Language::Persian,
        Language::Polish,
        Language::Portuguese,
        Language::Punjabi,
        Language::Quechua,
        Language::Romanian,
        Language::Romansh,
        Language::Rundi,
        Language::Russian,
        Language::NorthernSami,
        Language::Samoan,
        Language::Sango,
        Language::Sanskrit,
        Language::Sardinian,
        Language::Serbian,
        Language::Shona,
        Language::Sindhi,
        Language::Sinhala,
        Language::Slovak,
        Language::Slovenian,
        Language::Somali,
        Language::SouthernSotho,
        Language::Spanish,
        Language::Sundanese,
        Language::Swahili,
        Language::Swati,
        Language::Swedish,
        Language::Tagalog,
        Language::Tahitian,
        Language::Tajik,
        Language::Tamil,
        Language::Tatar,
        Language::Telugu,
        Language::Thai,
        Language::Tibetan,
        Language::Tigrinya,
        Language::Tonga,
        Language::Tsonga,
        Language::Tswana,
        Language::Turkish,
        Language::Turkmen,
        Language::Twi,
        Language::Uighur,
        Language::Ukrainian,
        Language::Urdu,
        Language::Uzbek,
        Language::Venda,
        Language::Vietnamese,
        Language::Volapuk,
        Language::Walloon,
        Language::Welsh,
        Language::Wolof,
        Language::Xhosa,
        Language::Yiddish,
        Language::Yoruba,
        Language::Zhuang,
        Language::Zulu,
    ];
}
