[package]
name = "save_json"
authors = ["John Bowling"]
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.23"
syn = { version = "2.0.4", features = ["extra-traits"] }

[dev-dependencies]
trybuild = { version = "1.0.77", features = ["diff"] }